### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by qmfrederik** [Kajabity/Kajabity-Tools#2]
Hi,

It would be helpful you could publish the Kajabity-Tools as a NuGet package.

I can prepare a PR that adds a NuGet package + AppVeyor support, if that's something you'd be interested in.

Thanks!

**Comment by Kajabity** [comment]
Thanks, I'm grateful for that offer, but as one major purpose of the site is for me to learn to do these things myself, I'd better get on with it!
I'd already planned to make Kajabity Tools a NuGet package but AppVeyor looks like a marvellous idea I wasn't aware of.

**Comment by Kajabity** [comment]
I have now added Kajabity Tools to AppVeyor (marvellous!) and setup to publish to nuget.org.
Have a look in the releases section here on GitHub to see the most up-to-date NuGet, DLL and EXE packages uploaded by AppVeyor.
