### ISSUE TITLE
Consider strongly naming the assemblies

### ISSUE THREAD

**Issue by qmfrederik** [Kajabity/Kajabity-Tools#4]
Hi,

Thanks for the NuGet package! 

Would you consider strongly naming the assemblies you provide, so they can also be used from strongly named projects?

Thanks!

**Comment by Kajabity** [comment]
I will certainly strongly consider it - but I've spent the last week trying to resolve issues with my hosting service and I need to fix that first.

**Comment by Kajabity** [comment]
I have added a key file and the nuget should now be uploaded in Strongly Name form.
